(*---------------------------------------------------------------------------
   Copyright (c) 2021 University of Bern. All rights reserved.
   SPDX-License-Identifier: ISC
  ---------------------------------------------------------------------------*)

(** Static data stamps.

    The implementation of this file is generated by the build system. *)

val static_files : string
(** [static_files] is a global stamp for direct page assets (css,
    fonts, etc.). This makes it easy to invalidate the browser cache
    on assets changes.

    {b FIXME.} On install this won't work if people tweak the files
    in the static directory, we should allow for this. *)

val version : string
(** [version] is a git describe stamp. *)
